"""empty message

Revision ID: 86c5f1868d54
Revises: 0ff6893a5d66
Create Date: 2021-03-31 20:42:38.779119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c5f1868d54'
down_revision = '0ff6893a5d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column', sa.Column('schema_id', sa.Integer(), nullable=False))
    op.drop_constraint('column_schema_fkey', 'column', type_='foreignkey')
    op.create_foreign_key(None, 'column', 'schema', ['schema_id'], ['id'])
    op.drop_column('column', 'schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column', sa.Column('schema', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'column', type_='foreignkey')
    op.create_foreign_key('column_schema_fkey', 'column', 'schema', ['schema'], ['id'])
    op.drop_column('column', 'schema_id')
    # ### end Alembic commands ###
